/* Generated by Yosys 0.60+67 (git sha1 96549e551, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* src = "adder16.v:1.1-12.10" *)
module adder16(A, B, Cin, Sum, Cout);
  (* src = "adder16.v:2.19-2.20" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "adder16.v:3.19-3.20" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "adder16.v:4.19-4.22" *)
  input Cin;
  wire Cin;
  (* src = "adder16.v:5.19-5.22" *)
  output [15:0] Sum;
  wire [15:0] Sum;
  (* src = "adder16.v:6.19-6.23" *)
  output Cout;
  wire Cout;
  (* src = "adder16.v:8.10-8.12" *)
  wire C8;
  (* module_not_derived = 32'd1 *)
  (* src = "adder16.v:10.12-10.56" *)
  adder8 u0 (
    .A(A[7:0]),
    .B(B[7:0]),
    .Cin(Cin),
    .Cout(C8),
    .Sum(Sum[7:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder16.v:11.12-11.58" *)
  adder8 u1 (
    .A(A[15:8]),
    .B(B[15:8]),
    .Cin(C8),
    .Cout(Cout),
    .Sum(Sum[15:8])
  );
endmodule

(* src = "adder32.v:1.1-12.10" *)
module adder32(A, B, Cin, Sum, Cout);
  (* src = "adder32.v:2.19-2.20" *)
  input [31:0] A;
  wire [31:0] A;
  (* src = "adder32.v:3.19-3.20" *)
  input [31:0] B;
  wire [31:0] B;
  (* src = "adder32.v:4.19-4.22" *)
  input Cin;
  wire Cin;
  (* src = "adder32.v:5.19-5.22" *)
  output [31:0] Sum;
  wire [31:0] Sum;
  (* src = "adder32.v:6.19-6.23" *)
  output Cout;
  wire Cout;
  (* src = "adder32.v:8.10-8.13" *)
  wire C16;
  (* module_not_derived = 32'd1 *)
  (* src = "adder32.v:10.13-10.59" *)
  adder16 u0 (
    .A(A[15:0]),
    .B(B[15:0]),
    .Cin(Cin),
    .Cout(C16),
    .Sum(Sum[15:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder32.v:11.13-11.60" *)
  adder16 u1 (
    .A(A[31:16]),
    .B(B[31:16]),
    .Cin(C16),
    .Cout(Cout),
    .Sum(Sum[31:16])
  );
endmodule

(* src = "adder4.v:1.1-30.10" *)
module adder4(A, B, Cin, Sum, Cout, Pout, Gout);
  (* src = "adder4.v:2.18-2.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "adder4.v:3.18-3.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "adder4.v:4.18-4.21" *)
  input Cin;
  wire Cin;
  (* src = "adder4.v:5.18-5.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "adder4.v:6.18-6.22" *)
  output Cout;
  wire Cout;
  (* src = "adder4.v:7.18-7.22" *)
  output Pout;
  wire Pout;
  (* src = "adder4.v:8.18-8.22" *)
  output Gout;
  wire Gout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "adder4.v:11.16-11.17" *)
  (* unused_bits = "1 2 3" *)
  wire [4:0] C;
  sky130_fd_sc_hd__nand2_1 _12_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__maj3_1 _14_ (
    .A(Cin),
    .B(A[0]),
    .C(B[0]),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__maj3_1 _16_ (
    .A(A[1]),
    .B(B[1]),
    .C(_02_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(A[2]),
    .B(B[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(_04_),
    .B(_05_),
    .X(Sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(_02_),
    .B(_03_),
    .Y(Sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(Cin),
    .B(_01_),
    .Y(Sum[0])
  );
  sky130_fd_sc_hd__maj3_1 _21_ (
    .A(A[2]),
    .B(B[2]),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(A[3]),
    .B(B[3]),
    .X(_07_)
  );
  sky130_fd_sc_hd__maj3_1 _23_ (
    .A(A[3]),
    .B(B[3]),
    .C(_06_),
    .X(Cout)
  );
  sky130_fd_sc_hd__nand3b_1 _24_ (
    .A_N(_03_),
    .B(_05_),
    .C(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand4_1 _25_ (
    .A(A[1]),
    .B(B[1]),
    .C(_05_),
    .D(_07_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a22o_1 _26_ (
    .A1(A[2]),
    .A2(B[2]),
    .B1(A[3]),
    .B2(B[3]),
    .X(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _27_ (
    .A1(A[3]),
    .A2(B[3]),
    .B1(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o211ai_1 _28_ (
    .A1(_00_),
    .A2(_08_),
    .B1(_09_),
    .C1(_11_),
    .Y(Gout)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(_01_),
    .B(_08_),
    .Y(Pout)
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(_06_),
    .B(_07_),
    .X(Sum[3])
  );
  assign { C[4], C[0] } = { Cout, Cin };
endmodule

(* top =  1  *)
(* src = "adder64.v:1.1-12.10" *)
module adder64(A, B, Cin, Sum, Cout);
  (* src = "adder64.v:2.19-2.20" *)
  input [63:0] A;
  wire [63:0] A;
  (* src = "adder64.v:3.19-3.20" *)
  input [63:0] B;
  wire [63:0] B;
  (* src = "adder64.v:4.19-4.22" *)
  input Cin;
  wire Cin;
  (* src = "adder64.v:5.19-5.22" *)
  output [63:0] Sum;
  wire [63:0] Sum;
  (* src = "adder64.v:6.19-6.23" *)
  output Cout;
  wire Cout;
  (* src = "adder64.v:8.10-8.13" *)
  wire C32;
  (* module_not_derived = 32'd1 *)
  (* src = "adder64.v:10.13-10.59" *)
  adder32 u0 (
    .A(A[31:0]),
    .B(B[31:0]),
    .Cin(Cin),
    .Cout(C32),
    .Sum(Sum[31:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder64.v:11.13-11.60" *)
  adder32 u1 (
    .A(A[63:32]),
    .B(B[63:32]),
    .Cin(C32),
    .Cout(Cout),
    .Sum(Sum[63:32])
  );
endmodule

(* src = "adder8.v:1.1-13.10" *)
module adder8(A, B, Cin, Sum, Cout);
  (* src = "adder8.v:2.18-2.19" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "adder8.v:3.18-3.19" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "adder8.v:4.18-4.21" *)
  input Cin;
  wire Cin;
  (* src = "adder8.v:5.18-5.21" *)
  output [7:0] Sum;
  wire [7:0] Sum;
  (* src = "adder8.v:6.18-6.22" *)
  output Cout;
  wire Cout;
  (* src = "adder8.v:8.10-8.12" *)
  wire C4;
  (* src = "adder8.v:9.14-9.16" *)
  (* unused_bits = "0" *)
  wire G0;
  (* src = "adder8.v:9.22-9.24" *)
  (* unused_bits = "0" *)
  wire G1;
  (* src = "adder8.v:9.10-9.12" *)
  (* unused_bits = "0" *)
  wire P0;
  (* src = "adder8.v:9.18-9.20" *)
  (* unused_bits = "0" *)
  wire P1;
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:11.12-11.59" *)
  adder4 u0 (
    .A(A[3:0]),
    .B(B[3:0]),
    .Cin(Cin),
    .Cout(C4),
    .Gout(G0),
    .Pout(P0),
    .Sum(Sum[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:12.12-12.60" *)
  adder4 u1 (
    .A(A[7:4]),
    .B(B[7:4]),
    .Cin(C4),
    .Cout(Cout),
    .Gout(G1),
    .Pout(P1),
    .Sum(Sum[7:4])
  );
endmodule
